### ISSUE TITLE
Choosing Model Parameters

### ISSUE THREAD

**Issue by The-Gupta** [numenta/nupic.workshop#5]
For a given dataset, how to find the right set of model parameters because they are just too many?
I know, swarming is for that. Can someone add more suggestions or even on how to getting started with swarming quickly?

**Comment by rhyolight** [comment]
Please see our [quick start guide](http://nupic.docs.numenta.org/stable/quick-start/index.html) and join [HTM Forum](https://discourse.numenta.org/search?q=model%20parameters) to ask questions.
